# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:..
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    sar -r -u 5 > system_usage.txt &
    echo $! > sar_pid.txt
  displayName: 'Start CPU and Memory monitoring'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    kill $(cat sar_pid.txt)
  displayName: 'Stop monitoring'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifact: drop

- task: PublishBuildArtifacts@1
  inputs:
   PathtoPublish: 'system_usage.txt'
   ArtifactName: 'SystemUsage'